### ISSUE TITLE
Stats GUI is blocking Train Menu Control Hints 

### ISSUE THREAD

**Issue by xilef310** [raiguard/Factorio-StatsGui#4]
### Description

![image](https://github.com/user-attachments/assets/9d23f986-4452-4ccc-8769-c866bf1411fd)

Is it possible to change this?

### Reproduction

1. Factorio 2.0
2. Select Train Menu for planning/sheduling.
3. Try to read the rop right control hint next to the research menu.
4. it is blockd

**Comment by xilef310** [comment]
Ah fuck I forgot there were settings. My bad.
I fixed it.

**Comment by raiguard** [comment]
This is actually a bug :)

**Comment by xilef310** [comment]
Oh lol. 
Thanks
