### ISSUE TITLE
Error while running event 

### ISSUE THREAD

**Issue by CarlosTorch** [raiguard/Factorio-StatsGui#8]
### Description

Error while running event StatsGui::on_player_created (ID 27)
Error when running interface function TLBE.recording_sensor: __TLBE__/scripts/camera.lua:496: attempt to index local 'playerSettings' (a nil value)
stack traceback:
	__TLBE__/scripts/camera.lua:496: in function <__TLBE__/scripts/camera.lua:493>
stack traceback:
	[C]: in function 'call'
	__StatsGui__/control.lua:157: in function 'sensor'
	__StatsGui__/scripts/stats-gui.lua:47: in function 'update'
	__StatsGui__/scripts/stats-gui.lua:25: in function 'build'
	__StatsGui__/scripts/player-data.lua:34: in function 'refresh'
	__StatsGui__/control.lua:40: in function <__StatsGui__/control.lua:37>

### Reproduction

On load saved file

**Comment by raiguard** [comment]
This is happening in TLBE, not StatsGui. Please report it to them.

**Comment by CarlosTorch** [comment]
Done, thanks
